repos:
-   repo: local
    hooks:
    -   id: patient_id
        name: Check for patient ids starting with "D", "H" or "M".
        always_run: true
        args: [--multiline]
        entry: '[DHM][0-9]{3}'
        language: pygrep
    -   id: OC-code-patient_id
        name: Check for patient ids starting with "OC".
        always_run: true
        args: [--multiline]
        entry: 'OC[0-9]{3}'
        language: pygrep
    -   id: EOC-patient_code
        name: Check for EOC patient codes.
        always_run: true
        args: [--multiline]
        entry: 'EOC[0-9]{3}'
        language: pygrep