[tool.poetry]
name = "oncodashkb"
version = "0.1.0"
description = "Knowledge graph build for oncodash using BioCypher"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
biocypher = "^0.11.0"
ontoweaver = "^1.0.0"
pooch = "^1.7.0"
pandas = "^2.3.1"
owlready2 = "^0.49"
pyarrow = "^20.0.0"
numpy = "^2.2.0"
ipykernel = "^6.29.5"
matplotlib = "^3.10.0"
polars = "^1.22.0"
seaborn = "^0.13.2"

[tool.poetry.dev-dependencies]
pytest = "^8.4.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
